### ISSUE TITLE
Installer recommends upgrade.php, but is unclear

### ISSUE THREAD

**Issue by t4k** [Coral-erm/Coral#187]
I ran through the Installer today and noticed that it recommended running upgrade.php when the databases existed. It did not give a link or a path to the file. The only modules it exists for are Organizations and Reports.

This should probably be made a little more clear. I'm not sure the exact steps to go through to make this do what we think.

**Comment by jcuenod** [comment]
It definitely shouldn't be recommending running `upgrade.php`. Thanks for catching this. I'll take a look but I think this may be something hanging over from an early iteration of the installer code.

**Comment by jcuenod** [comment]
Good catch, thanks! I haven't read that message for too long :)

The problem is at https://github.com/Coral-erm/Coral/blob/master/install/providers/db_tools.php#L173

I've just removed that sentence so the message now reads, "The tables for %s already exist. If you would like to perform a fresh install you will need to delete all of the tables in this schema first. Alternatively, if your tables are prepopulated, you can continue the install and we will assume that they are set up correctly."

The upgrade should happen automatically - that was something that was only decided after this message was originally written. So you're right there's no need for it. The commit is part of #186, see https://github.com/Coral-erm/Coral/pull/186/commits/7ea2b1f118b21843a451b9e96f44c4938b83376c
