### ISSUE TITLE
Rational behind limiting Sushi pulls to  one year

### ISSUE THREAD

**Issue by infoseek1** [coral-erm/coral#204]
Why are errors generated when attempting to pull a SUSHI Statistics for more than one year?
Does anyone from the original team know why the limit exists?
Is it a memory handling issue? Or something else?

[https://github.com/Coral-erm/Coral/blob/238e7a7a5a3c5953685e5c128790951a106af99e/usage/ajax_processing.php](url)

**Comment by jeffnm** [comment]
There were serious issues https://github.com/ndlibersa/usage/issues/25 with the way the import was detecting the year and when fixing that and adding the ability to import months across calendar years (e.g. fiscal years) it became necessary to limit imports to 12 months or it became impossible to know which year the given month belonged to and you would start getting data corrupted as months would overwrite each other. At least, that's my recollection. I believe the original code restricted imports to the current calendar year, which was even more limited. 

CORAL tries to only get months since the last SUSHI import, so for most users with cron jobs set for their SUSHI schedule this shouldn't be an issue. It's obviously a frustration for users who are just starting out with their Usage Statistics though.

**Comment by cjc66** [comment]
We noticed that if you try to load a year's worth of statistics from 2016 that it fails, possibly because 2016 was a leap year?  I can harvest a range of 01-01-2016 - 12-30-2016, but it fails if I try 01-01-2016 - 12-31-2016.

**Comment by remocrevo** [comment]
@cjc66 You are exactly right.  The code limits to 365 days (in seconds) here:

https://github.com/Coral-erm/Coral/blob/master/usage/admin/classes/domain/SushiService.php#L488

**Comment by andyp-uk** [comment]
The changes in PR #660 result in being able to import across a range of calendars in one action—for example, to request data with a begin date of 1 Dec 2019 and end date of 31 Jan 2020. The changes also address the issue whereby the date range is limited to 365 days (31536000 seconds). There is, in my opinion, a separate issue related to the design insofar as the current workflow requires you to review (view) the data in the report before you can import it; this tends to discourage the user from importing a large range of data all at once.

**Comment by rtatterson** [comment]
Resolved.
