### ISSUE TITLE
Documentation of Coral Workflow?

### ISSUE THREAD

**Issue by infoseek1** [coral-erm/coral#21]
Hello,
I found the data models, and looking for the  mapped out the workflows of the various modules in practice?

**Comment by jeffnm** [comment]
@infoseek1 I don't have the answer, but I've passed it on to others who might.

**Comment by scottvieira** [comment]
@infoseek1 I'm not aware of any mapped out workflows.  I'm assuming we are talking about ER workflows with CORAL.  My approach to CORAL has been to leverage its flexibility around the existing institutional/ER workflows.  Because of this flexibility I believe many libraries are using CORAL selectively and differently.  However for the future, I like the idea your question suggests of a best practices document for CORAL.  For now to explore different workflow options I would talk to libraries using CORAL to get a range of ideas.  Asking the CORAL discussion listserv (CORAL-ERM@LISTSERV.ND.EDU) has worked well for others in asking similar questions.

**Comment by infoseek1** [comment]
Yes best practices would be good as for smaller schools workflows are not fully documented. 
https://library3.hud.ac.uk/blogs/terms/   has some info. Thinking a CORAL Version of http://toolkit.idsproject.org/

**Comment by xsong9** [comment]
Resolved.
