### ISSUE TITLE
Slowness with keyword searches in Resources

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/coral#256]
The initial list of resources that displays in the Resources module takes 1-3 seconds to load when there are several thousand (in our case, about 7,800) records. Also, keyword searches in the Name field can take a similar amount of time to retrieve results.

**Comment by queryluke** [comment]
@techsvcslib A Sirsi custom mer with 127,000+ records also mentioned slowness on the resource search page. I poked around with the queries and code and here is my analysis.

# Method

In order to troubleshoot this issue, I wrote [a script](https://gist.github.com/queryluke/93a3dfedc5be49bc1ee29d0ffd13209e) which seeds 250,000 dummy records in a local MySQL db.

# Baseline

Here is the base Resource query:

```sql
SELECT
	R.resourceID,
	R.titleText,
	GROUP_CONCAT(DISTINCT AT.shortName SEPARATOR ' / ') as acquisitionType,
	R.createLoginID,
	CU.firstName,
	CU.lastName,
	R.createDate,
	S.shortName status,
	GROUP_CONCAT(DISTINCT A.shortName, I.isbnOrIssn ORDER BY A.shortName DESC SEPARATOR ' ') aliases
FROM Resource R
LEFT JOIN ResourceAcquisition RA ON R.resourceID = RA.resourceID
LEFT JOIN Alias A ON R.resourceID = A.resourceID
LEFT JOIN ResourceOrganizationLink ROL ON R.resourceID = ROL.resourceID
LEFT JOIN coral_organizations.Organization O ON O.organizationID = ROL.organizationID
LEFT JOIN coral_organizations.Alias OA ON OA.organizationID = ROL.organizationID
LEFT JOIN ResourceRelationship RRC ON RRC.relatedResourceID = R.resourceID
LEFT JOIN ResourceRelationship RRP ON RRP.resourceID = R.resourceID
LEFT JOIN ResourceSubject RSUB ON R.resourceID = RSUB.resourceID
LEFT JOIN Resource RC ON RC.resourceID = RRC.resourceID
LEFT JOIN Resource RP ON RP.resourceID = RRP.relatedResourceID
LEFT JOIN GeneralDetailSubjectLink GDLINK ON RSUB.generalDetailSubjectLinkID = GDLINK.generalDetailSubjectLinkID
LEFT JOIN AcquisitionType AT ON RA.acquisitionTypeID = AT.acquisitionTypeID
LEFT JOIN Status S ON R.statusID = S.statusID
LEFT JOIN User CU ON R.createLoginID = CU.loginID
LEFT JOIN IsbnOrIssn I ON R.resourceID = I.resourceID
WHERE R.statusID != 3
GROUP BY R.resourceID
ORDER BY R.createDate DESC, TRIM(LEADING 'THE ' FROM UPPER(R.titleText)) asc
LIMIT 0, 25
```

The primary issue is with the `ORDER BY` clause. MySQL is notoriously slow
when ordering large datasets. For the above query, my execution times are
between 7 and 8 seconds.

There are currently 14 different `ORDER BY` variations:
- new search (no order by)*
- on page load* +
- (2) title asc & desc
- (2) ID asc & desc**
- (2) Creator asc & desc**
- (2) Date Created asc & desc**
- (2) Acquisition Type asc & desc**
- (2) Status asc & desc**

\* _the New Search button does not sort but a page refresh does_
\** _These are all additionally sorted by the title SQL, but I have not replicated the exact code for readability's sake._
\+ _The page load sort does not include the translations for `THE`_

### Runtimes

Sort | ORDER BY SQL | Time (seconds)
--- | --- | ---
New Search* | (no sort) | .01s
Page Load* | `ORDER BY R.createDate DESC, TRIM(LEADING 'THE ' FROM UPPER(R.titleText))` | 7.54s
Title | `ORDER BY TRIM(LEADING 'THE ' FROM (TRIM(LEADING 'EL ' FROM (TRIM(LEADING 'L\'' FROM (TRIM(LEADING 'LA ' FROM (TRIM(LEADING 'LE ' FROM (TRIM(LEADING 'LES ' FROM (TRIM(LEADING 'DER ' FROM (TRIM(LEADING 'DIE ' FROM (TRIM(LEADING 'DAS ' FROM UPPER(R.titleText))))))))))))))))))` | 8.51s
ID | `ORDER BY R.resourceID + 0` | 7.77s
Creator | `ORDER BY CU.loginID` | 8.18s
Date Created | `ORDER BY R.createDate desc` | 8.21s
Acquisition Type | `ORDER BY acquisitionType` | 8.20s
Status | `ORDER BY S.shortName` | 7.79s



# Temporary Table Solution

One possible solution is to create a temporary table of ResourceIDs and `INNER JOIN`
that table into the query. Here is an example:

```sql
DROP TEMPORARY TABLE IF EXISTS get_resources;

CREATE TEMPORARY TABLE get_resources
	SELECT resourceID FROM Resource WHERE statusID != 3 ORDER BY createDate DESC, TRIM(LEADING 'THE ' FROM UPPER(titleText)) LIMIT 0, 25;

SELECT
	R.resourceID,
	R.titleText,
	R.createDate,
	GROUP_CONCAT(DISTINCT AT.shortName SEPARATOR ' / ') as acquisitionType,
	R.createLoginID,
	CU.firstName,
	CU.lastName,
	S.shortName status,
	GROUP_CONCAT(DISTINCT A.shortName, I.isbnOrIssn ORDER BY A.shortName DESC SEPARATOR ' ') aliases
FROM get_resources tempR
INNER JOIN Resource R ON tempR.resourceID = R.resourceID
LEFT JOIN ResourceAcquisition RA ON R.resourceID = RA.resourceID
LEFT JOIN Alias A ON R.resourceID = A.resourceID
LEFT JOIN ResourceOrganizationLink ROL ON R.resourceID = ROL.resourceID
LEFT JOIN coral_organizations.Organization O ON O.organizationID = ROL.organizationID
LEFT JOIN coral_organizations.Alias OA ON OA.organizationID = ROL.organizationID
LEFT JOIN ResourceRelationship RRC ON RRC.relatedResourceID = R.resourceID
LEFT JOIN ResourceRelationship RRP ON RRP.resourceID = R.resourceID
LEFT JOIN ResourceSubject RSUB ON R.resourceID = RSUB.resourceID
LEFT JOIN Resource RC ON RC.resourceID = RRC.resourceID
LEFT JOIN Resource RP ON RP.resourceID = RRP.relatedResourceID
LEFT JOIN GeneralDetailSubjectLink GDLINK ON RSUB.generalDetailSubjectLinkID = GDLINK.generalDetailSubjectLinkID
LEFT JOIN AcquisitionType AT ON RA.acquisitionTypeID = AT.acquisitionTypeID
LEFT JOIN Status S ON R.statusID = S.statusID
LEFT JOIN User CU ON R.createLoginID = CU.loginID
LEFT JOIN IsbnOrIssn I ON R.resourceID = I.resourceID
GROUP BY R.resourceID
ORDER BY R.createDate DESC, TRIM(LEADING 'THE ' FROM UPPER(R.titleText));

DROP TEMPORARY TABLE IF EXISTS get_resources;
```

### Runtimes

Sort | ORDER BY SQL | Time (sec)
--- | --- | ---
New Search | (no sort) | .1s
Page Load | `ORDER BY R.createDate DESC, TRIM(LEADING 'THE ' FROM UPPER(R.titleText))` | .52s
Title | `ORDER BY TRIM(LEADING 'THE ' FROM (TRIM(LEADING 'EL ' FROM (TRIM(LEADING 'L\'' FROM (TRIM(LEADING 'LA ' FROM (TRIM(LEADING 'LE ' FROM (TRIM(LEADING 'LES ' FROM (TRIM(LEADING 'DER ' FROM (TRIM(LEADING 'DIE ' FROM (TRIM(LEADING 'DAS ' FROM UPPER(R.titleText))))))))))))))))))` | .49s
ID | `ORDER BY R.resourceID + 0` | .52s
Creator* | `ORDER BY CU.loginID` | 1.06s
Date Created | `ORDER BY R.createDate desc` | .49s
Acquisition Type* | `ORDER BY acquisitionType` | 1.68s
Status* | `ORDER BY S.shortName` | 1.20s

\* _Required left joins from other tables_

__Caveats__
1. The temp table name `get_resources` will need to have some sort of timestamp. Otherwise,
if two people are searching at the same time, the latter person's query will destroy
the table of the already running query.
2. The execution time increases with the offset. For example, the page load query executes in ~ .5s.
With `LIMIT 1000, 25` execution increases to 1.6s. 10,000 = 2s & 100,000 = 3s.
3. All where clauses will need to be passed to the temporary table creation. This would
require a large amount of refactoring to the query construction scripts to ensure only the necessary
tables are joined.

# View solution

Another approach I've used is creating a view for each sort type. The benefit of this approach
is that query construction in php is simpler because the pre-sorted table is used
instead of the Resource table. An example query would be:

```sql
SELECT
	R.resourceID,
	R.titleText,
	R.createDate,
	GROUP_CONCAT(DISTINCT AT.shortName SEPARATOR ' / ') as acquisitionType,
	R.createLoginID,
	CU.firstName,
	CU.lastName,
	S.shortName status,
	GROUP_CONCAT(DISTINCT A.shortName, I.isbnOrIssn ORDER BY A.shortName DESC SEPARATOR ' ') aliases
FROM v_createDate_desc_title_asc R
LEFT JOIN ResourceAcquisition RA ON R.resourceID = RA.resourceID
LEFT JOIN Alias A ON R.resourceID = A.resourceID
LEFT JOIN AcquisitionType AT ON RA.acquisitionTypeID = AT.acquisitionTypeID
LEFT JOIN Status S ON R.statusID = S.statusID
LEFT JOIN User CU ON R.createLoginID = CU.loginID
LEFT JOIN IsbnOrIssn I ON R.resourceID = I.resourceID
WHERE R.statusID != 3
GROUP BY R.resourceID
LIMIT 0, 25
```

In this case, `v_createDate_desc_title_asc` is the pre-sorted view. Meaning that
constructing the query only requires a map of the user's selected sort and the corresponding
view.

Unfortunately, my testing proved only marginal improvements in execution time.

### Runtimes
Sort | ORDER BY SQL | Time (sec)
--- | --- | ---
New Search | (no sort) | .01s
Page Load | `ORDER BY R.createDate DESC, TRIM(LEADING 'THE ' FROM UPPER(R.titleText))` | 5.64s
Title | `ORDER BY TRIM(LEADING 'THE ' FROM (TRIM(LEADING 'EL ' FROM (TRIM(LEADING 'L\'' FROM (TRIM(LEADING 'LA ' FROM (TRIM(LEADING 'LE ' FROM (TRIM(LEADING 'LES ' FROM (TRIM(LEADING 'DER ' FROM (TRIM(LEADING 'DIE ' FROM (TRIM(LEADING 'DAS ' FROM UPPER(R.titleText))))))))))))))))))` | 6.83s
ID | `ORDER BY R.resourceID + 0` | 5.57s
Creator* | `ORDER BY CU.loginID` | 6.17s
Date Created | `ORDER BY R.createDate desc` | 5.64s
Acquisition Type* | `ORDER BY acquisitionType` | 10.93s
Status* | `ORDER BY S.shortName` | 6.23s

### Other ideas?

If anyone has any other options they'd like me to try, please comment. Otherwise, it
looks like the best solution will be the temporary table route.

**Comment by queryluke** [comment]
In addition to everything above another potential solution is to remove the default sort when there are 50,000+ resource records. There might be a few filters (like the A-Z filters) where a default sort could be applied.

The issue that a SirsiDynix client is having is that the default sort `ORDER BY R.createDate DESC, TRIM(LEADING 'THE ' FROM UPPER(R.titleText))` for 100,000+ records is taking ~ 30 seconds to load. The workaround has been to set `defaultsort = " "` in the configuration file.

**Comment by jcuenod** [comment]
I hope I'm correct in understanding what problem is being referenced here - feel free to tell me this is off topic...

I think the PR that I'm working on makes this initial load quite a bit faster. On this topic though, `ORDER BY` is slow when there are lots of results to order. This slows down the initial query which can be improved by doing fewer joins (which my PR sets about trying to do). I think here, though, queries on `Name (contains)` are slow because of the `WHERE`.

When I was looking at this I came to believe that a major slowdown was being caused by the fact that text comparisons were being done on multiple fields in multiple places. See these lines particularly:

https://github.com/coral-erm/coral/blob/master/resources/admin/classes/domain/Resource.php#L530-L539

These queries are particularly slow because:
1. `LIKE` is slow
2. `LIKE` is slower with wildcards (and all of these have `%`)
3. I don't think these tables all have indices on the columns referenced (this might be an easy way to speed things up but I think I may tried adding indices and it wasn't a dramatic improvement. I can't remember any more)

The right solution is probably to use `FTS` but I don't think it's a practical solution here.
