### ISSUE TITLE
Required layout for book reports in Usage Statistics is incorrect

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/coral#257]
When manually loading COUNTER BR1 or BR2 book reports (R4), CORAL Usage Statistics incorrectly errors out when the header row containing column headers for "Publisher", "Platform", "DOI", "Proprietary Identifier", "ISBN", "ISSN", "Reporting Period Total", "Jan-2017", etc. does not start with "Title" in the first column. This directly contradicts the definition of these reports by Project COUNTER. To get these properly formatted reports to load, you have to manually edit them to insert "Title" in the very first column of the header row. The layout definition within CORAL needs to be updated to fix this.

**Comment by andyp-uk** [comment]
To clarify, the issue seems to be that Cell A8 in the tabular R4 BR1 and BR2 reports is actually meant to be blank, according to the examples provided by Project Counter. CORAL uses these values to validate the layout and expects the R4 book reports to use a literal value of "Title":
https://github.com/coral-erm/coral/blob/master/usage/layouts.ini#L152
