### ISSUE TITLE
Numbers internationalization 

### ISSUE THREAD

**Issue by veggiematts** [coral-erm/coral#311]
Currently, in Coral, the only representation of numbers is the american one, but numbers representation depends on the country. For example:

The number 9988776.65 will be:
 - 9 988 776,65 in France
 - 9.988.776,65 in Germany
 - 9,988,776.65 in the United States

That's a problem, because:

1) It's counter-intuitive for the users to enter numbers, now that Coral is translated
2) exported data will be hard to process by other softwares that are aware of country-formatting specifics.

I made a proof of concept for the payment amounts in cost history, available here:
https://github.com/biblibre/Coral/tree/payment_amounts_i18n

It's not a pull request yet, because it is incomplete, and may have broken other things in Coral, and is only for the resources module right now, but I wanted your opinion about it.

It uses PHP NumberFormatter class: http://php.net/manual/en/class.numberformatter.php
It is a new dependency that would be needed for Coral, but it seems to be packaged in most distributions (package php-intl on ubuntu)

Please have a look at the code, it's a small patch, and NumberFormatter is really easy to use.

You can simply test it by changing the translation, and checking that the payment amounts are displayed according to the selected language.

If you want to modify payment amounts, it also works, but please note that the payment amount related javascript has been disabled for this POC, so the price will not be calculated from the tax rate, and the form will not check that the input is a number.

If you agree that this is the direction we should be headed to, I'll have a closer look on how to handle numbers i18n in javascript.

**Comment by poacherone** [comment]
I haven't looked at the actual code at the repo that @veggiematts refers to, but in general this type of solution as absolutely needed. However, I am not too keen to see a solution where this is set by the selected language, simply because there is no 1 to 1 relationship between language and numbers representation. It would be best if this was configurable instead.

**Comment by veggiematts** [comment]
"However, I am not too keen to see a solution where this is set by the selected language, simply because there is no 1 to 1 relationship between language and numbers representation. It would be best if this was configurable instead."

It could be done as language selection in web-apps: default language is based on what the browsers says it likes most, and then the user can choose another language.
In our case, the default format could be based on the user language, then changed if needed.

**Comment by veggiematts** [comment]
So, to sum things up, we need to be able to use custom number formats in 3 places:

 - PHP code (using PHP NumberFormatter)
 - Javascript code (using ?)
 - SQL queries (like in resources exports and dashboards, for example) (using custom code?)

**Comment by poacherone** [comment]
Yes that seems like a good summary.

On your previous comment, yes we could approach it in such a way. The main concern is that it will actually be possible to change the format, regardless of the language. I don't know how more difficult it would be code-wise, but I'm assuming your suggestion means changing language an currency on the fly in the UI? Because changes need to be reflected in the three places you mention it sound to me like a large operation?

I would think just a value you set in a configuration file, would be an easier option? But perhaps not as powerful? (I can imagine a use can with staff using different configurations, in organizations using Coral who are cross-national.)

**Comment by veggiematts** [comment]
For SQL queries, we could perhaps use the FORMAT function: 
`FORMAT(X,D[,locale])`

> The optional third parameter enables a locale to be specified to be used for the result number's decimal point, thousands separator, and grouping between separators. 

https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_format
