### ISSUE TITLE
Installer Failed: $db_info empty

### ISSUE THREAD

**Issue by tmarnell** [coral-erm/coral#332]
I installed CORAL for my institution today and, at the end of the process, got stuck on this error:

"Database access was denied from @. Please ensure that you can access the database with the password you provided."

In install/providers/have_default_db_user.php, line 159 shows that the database username and host should have been printed on either side of the @. When I added die(var_dump($db_info)); within the switch statement, I found $db_info was null. The array was properly defined in line 136, but didn't make it into the anonymous function on line 142.

So in line 142, I added $db_info to the use construct, and then the installation completed without errors.

**Comment by jeffnm** [comment]
@jcuenod I never noticed this issue when it was originally opened. Can you take a look at it? I see that `$db_info` is used on line 144, but not 142. Is there an edge case that this would fail on, but work for most installs?

**Comment by veggiematts** [comment]
I can confirm this bug.
For me, it happened when doing so:

On the screen that says 

> "To begin with, we need a username and password to create the databases CORAL and its modules will be using."

I entered a non-admin mysql user.

The installer tries to revoke the coral user rights:
`providers/have_default_db_user.php, line 119:`
`$db->processQuery("REVOKE ALL ON {$db_details["dbname"]}.* FROM {$db_details["username"]}@{$db_details["host"]}");`

Since the user I entered did not have the rights to do so, the REVOKE failed, returning a 1045 error:

`$return->yield->messages[] = _("Database access was denied from {$db_info["username"]}@{$db_info["host"]}. Please ensure that you can access the database with the password you provided.");`

I can also confirm that `$db_info["username"]` and `$db_info["host"]` were empty.

**Comment by jcuenod** [comment]
Yup, thanks @veggiematts! I guess this hasn't been picked up on is that people have been entering admin users pretty reliably.

I also notice that 142 has some parameters that I don't think are used. So I think it should be:

    "bundle" => function($version = 0) use ($config_files, $db_info) {

**Comment by veggiematts** [comment]
By the way, maybe it's just me, but I think the installer is not saying clearly enough that an admin user is required.

**Comment by jeffnm** [comment]
Thanks @veggiematts that's good to know. It's the kind of thing that once you've run it over and over again you stop even reading the notice because you know what is needed.
