### ISSUE TITLE
workflow / routing

### ISSUE THREAD

**Issue by PaulPoulain** [Coral-erm/Coral#34]
In the Resource module, the term "workflow" is used, while the tab in the resource is called "routing".
We must be consistent.
As the DB table is called "Workflow", I suggest to rename "routing" to "workflow" for the resource tab

**Comment by benheet** [comment]
I think we called it routing because during the initial creation we based the feature off of a physical routing slip that went from one persons desk to another. I have no objection to calling the feature Workflow in all instances and dropping the Routing designation.

**Comment by techsvcslib** [comment]
I agree with Ben.

**Comment by PaulPoulain** [comment]
I've added the "bug" label, as I think inconsistency in vocabulary is a bug.
I'll try to provide a PR asap

**Comment by techsvcslib** [comment]
I agree with you on calling this a bug :-)

Steve

**Comment by jeffnm** [comment]
@PaulPoulain It looks like this didn't get patched. Since there is another pull request blocking 2.0.0 RC this week, there is a little more time to get this patch in, if you want.

**Comment by PaulPoulain** [comment]
@veggiematts can you work on a fix, thanks

**Comment by scottvieira** [comment]
@PaulPoulain and @jeffnm Do we want to change the "routing step" label on the search for 2.0 too?  If so, I would like to get this done soon, so we can start updating the documentation.

**Comment by scottvieira** [comment]
@t4k Tommy I'm adding you to this discussion as I just realized that Jeff may be out.  I'm thinking we would want to get this wording changed before the 2.0 final release.

**Comment by t4k** [comment]
I’m not exactly familiar with this history, but if I were to create a pull request, would a good approach be to do a search on “Routing Step” and replace all the instances with “Workflow Step”? I would exclude the `resources/ReleaseNotes` file.

What about the .po translation files? I don’t have any experience working with translations and I’m unsure if it would be appropriate to replace the string in those files or not because it might make the translation incorrect.

<img width="891" alt="routing_step" src="https://cloud.githubusercontent.com/assets/415179/26645711/eaa2975a-45ed-11e7-958f-0b5ccb15fd04.png">

**Comment by scottvieira** [comment]
@tk4 Yes, I would think so.  The original intention of this PR was to update the language so that it was the same throughout CORAL.  For what I can tell, the "routing step" under the search form was missed and should be changed to "workflow step".  In regards to the translation files, unfortunately I'm not familiar with these, maybe @PaulPoulain can comment.

**Comment by cjc66** [comment]
I will check with our folks as well to see what needs to be done regarding the .po files, we can probably help with that.

**Comment by cjc66** [comment]
I checked with Brad, who worked with our translator on the Chinese translations, and he sent this comment:

You need to use an editor to edit the translation files. There are a few of them out there, but POEDIT ( https://poedit.net/ ) seems to work the best.  POEDIT will parse the PHP and JavaScript files and pull out all of the strings into a translation table.  This keeps the translation files in sync with the project. The documentation on how to use POEDIT is also on the site listed above.  Since the po files reside at the root of each module, the base directory needs to point there, so for the Resources module, the root/base directory would be something like c:\apache24\htdocs\coral\resources.

The main thing to note: If no translation is supplied for a string in a given language, it will appear as it does in the program (i.e. English).  Having said that, it is best to make sure you have translations for the new strings in all of the languages currently supported by Coral before modifying the translation files.

**Comment by remocrevo** [comment]
There is also a CORAL wiki page about translations:

https://github.com/Coral-erm/Coral/wiki/Translation-of-ERMS-CORAL

Remington

--
Remington Steed
Electronic Resources Specialist
Hekman Library, Calvin College
http://library.calvin.edu/

**Comment by t4k** [comment]
My pull request does not include the translations. Is this the only issue delaying release of 2.0.0?

**Comment by t4k** [comment]
@scottvieira, can you review the pull request to make sure it solves this issue?

**Comment by scottvieira** [comment]
@t4k it looks good to me.  I can't speak for the translations, although when the other labels were updated by @PaulPoulain I'm not sure if the translations were updated either, or even needed to be.

**Comment by scottvieira** [comment]
@tk4 Mang @fondrenlibrary reviewed the Mandarin.  He actually knows French too.  He says it is acceptable.  I suspect there isn't much difference in translation between routing and workflow anyway.  We can also update the translations table later if better terms are decided upon.

**Comment by t4k** [comment]
Closing this issue. If anything related to translations comes up again a new issue can be created.
