### ISSUE TITLE
ubable to pass data to mysql using php

### ISSUE THREAD

**Issue by aravindrnair05** [coral-erm/coral#706]
When I tried to install coral this error is showing I installed all pre-requite software (apache, MySQL, PHP, php-mbstring, PHP-MySQL, php-common) is this issue is because of any extensions I missed. Please replay important work
![coral](https://user-images.githubusercontent.com/49126622/177920047-e3c3997d-72fd-434c-a30b-83832fd3bef8.png)

**Comment by LuckyGuyMike** [comment]
@aravindrnair05 
This problem is caused by the way MySQL handles the authentication ("auth_socket") vs "mysql_native_password".
The fix: Switch the authentication method, continue with the install, and then change it back when installation finishes.

-Here's a reference link that has the steps you'll need to use: https://devanswe.rs/how-to-fix-failed-error-set-password-has-no-significance-for-user-rootlocalhost/
